import React, { useState, useEffect } from 'react'
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import { Button, Row, Col } from 'antd';
import CardComponent from '../components/card';
import { fadeIn } from 'react-animations';
import Radium, { StyleRoot } from 'radium';
import LayoutCustom  from '../components/layoutCustom';
import { useRouter } from 'next/router'
import ModalDetailProduct from '../components/modalDetailProduct'
import { useDispatch, useSelector } from 'react-redux';
import { getListMerchandise, setListMerchandise } from '../storeRedux/actions/actionCreator'
import ImageNext from 'next/image'
export default function Home() {

  const router = useRouter()

  const dispatch = useDispatch()
  const dataListMerchandise = useSelector(state => state.clientReducer.dataListMerchandise)
  const loadingMerchandise = useSelector(state => state.clientReducer.loadingMerchandise)

  const [dataHotProduct, setDataHotProduct] = useState([])
  const [dataSkeleton] = useState([1,2,3,4,5,6,7,8])

  useEffect(() => {
    dispatch(getListMerchandise({ page: 1, limit: 8 }))
  }, [])

  useEffect(() => {
    if(dataListMerchandise) {
      setDataHotProduct(dataListMerchandise.data)
    }
  }, [dataListMerchandise])

  useEffect(() => () => {
    setDataHotProduct([])
    dispatch(setListMerchandise({}))
  }, [])

  const handleBuyMerchandise = () => {
    router.push('/merchandise')
  }

  const handleBookingBarber = () => {
    router.push('/bookingBarber')
  }

  return (
    <LayoutCustom className={styles.container}>
      <Head>
        <title>M BarberShop</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section style={{ height: '100vh' }}>
        <div className={styles.styleBackground}>
          <div>
            <ImageNext src="/assets/RS37761_GettyImages-506514876.jpg" layout='fill' />
          </div>
          <div className={styles.wrapperBackground}>
            <div className={styles.textBarbershop}>M BarberShop</div>
            <div className={styles.textSlogan}>The Future of BarberShop</div>
            <div style={{ display: 'flex', flexDirection: 'row', marginTop: '1rem' }}>
              <Button className={`${styles['ant-btn']} ${styles['ant-btn-lg']}`} style={{ marginRight: '1rem', background: 'transparent', color: 'white', fontWeight: 400 }} size="large" onClick={() => handleBookingBarber()}>Book Now</Button>
              <Button className={`${styles['ant-btn']} ${styles['ant-btn-lg']}`} size="large" style={{ color: 'black', fontWeight: 400, background: 'white' }} onClick={() => handleBuyMerchandise()}>Buy Merchandise</Button>
            </div>
          </div>
        </div>
      </section>

      <StyleRoot>
        <section style={{ padding: '50px 0 8px 0' }}>
          <div style={styleAnimation.fadeIn}>
            <Row>
              <Col span={24} style={{ display: 'flex', flexDirection: 'column', justifyContent: 'center', alignItems: 'center' }}>
                <h2 className={styles.textHotProduct}>HOT PRODUCT</h2>
                <p className={styles.textDescriptionProduct}>Come up with new fashion and be the center of attention</p>
              </Col>
            </Row>
            <div style={{ display: 'flex', flexDirection: 'column', justifyContent: 'space-around' }}>
              <div>
                {
                  loadingMerchandise ?
                  (
                    <Row gutter={[16,16]} style={{ marginLeft: 0, marginRight: 0 }}>
                      {
                        dataSkeleton && dataSkeleton.map((_data, index) => {
                          return (
                            <Col key={index} className="gutter-row" span={6} lg={6} md={12} sm={12} xs={12}>
                              <CardComponent />
                            </Col>
                          )
                        })
                    }
                    </Row>
                  )
                  :
                  (
                    <Row gutter={[16,16]} style={{ marginLeft: 0, marginRight: 0 }}>
                      {
                        dataHotProduct && dataHotProduct.map((data, index) => {
                          return (
                            <Col key={index} className="gutter-row" span={6} lg={6} md={12} sm={12} xs={12}>
                              <CardComponent name={data.name} price={data.sellingPrice} sourceImage={data.imageUrl} id={data.id} data={data} />
                            </Col>
                          )
                        })
                      }
                    </Row>
                  )
                }
              </div>
            </div>
          </div>
        </section>
      </StyleRoot>
      <ModalDetailProduct/>
    </LayoutCustom>
  )
}

const styleAnimation = {
  fadeIn: {
    animation: 'x 3s',
    animationName: Radium.keyframes(fadeIn, 'fadeIn'),
  }
}